version: "3.8"

networks:
  gva-net:
    driver: bridge
    name: gva-net

volumes:
  web-data:
  admin-data:
  bot-data:
  mysql-data:
  redis-data:

services:
  gva-mysql:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: gva
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - gva-net

  gva-redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass  password
    volumes:
      - redis-data:/data
    networks:
      - gva-net

  gva-backend-web:
    depends_on:
      - gva-mysql
      - gva-redis
    env_file:
      - env/docker.local.env
    build:
      context: .
      dockerfile: ./build/Dockerfile.web
    volumes:
      - web-data:/app
    networks:
      - gva-net
    ports:
      - 5500:5500

  gva-backend-admin:
    depends_on:
      - gva-mysql
      - gva-redis
    env_file:
      - env/docker.local.env
    build:
      context: .
      dockerfile: ./build/Dockerfile.admin
    volumes:
      - admin-data:/app
    networks:
      - gva-net
    ports:
      - 5501:5501

  gva-backend-bot:
    depends_on:
      - gva-mysql
      - gva-redis
    env_file:
      - ./env/docker.local.env
    build:
      context: .
      dockerfile: ./build/Dockerfile.bot
    volumes:
      - bot-data:/app
    networks:
      - gva-net
    ports:
      - 5502:5502
