basePath: /
definitions:
  dto.AdminRequest:
    type: object
  dto.PermissionRequest:
    type: object
  dto.RoleRequest:
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      errors:
        items: {}
        type: array
      messages:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: GO VUE ADMIN Boilerplate
  title: GVA API
  version: "1.0"
paths:
  /admin:
    get:
      consumes:
      - application/json
      description: Get a list of all Admins
      operationId: list-all-Admins
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Admins
          schema:
            $ref: '#/definitions/response.Response'
      summary: List all Admins
      tags:
      - Admin
    post:
      consumes:
      - application/json
      description: Create a new Admin with the provided details
      operationId: create-Admin
      parameters:
      - description: Admin data
        in: body
        name: Admin
        required: true
        schema:
          $ref: '#/definitions/dto.AdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created Admin
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create a Admin
      tags:
      - Admin
  /admin/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Admin by ID
      operationId: delete-Admin-by-id
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted Admin
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete a Admin
      tags:
      - Admin
    get:
      consumes:
      - application/json
      description: Get a Admin by ID
      operationId: get-Admin-by-id
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get a Admin
      tags:
      - Admin
    patch:
      consumes:
      - application/json
      description: Update a Admin by ID
      operationId: update-Admin-by-id
      parameters:
      - description: Admin ID
        in: path
        name: id
        required: true
        type: integer
      - description: Admin data
        in: body
        name: Admin
        required: true
        schema:
          $ref: '#/definitions/dto.AdminRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated Admin
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update a Admin
      tags:
      - Admin
  /permission:
    get:
      consumes:
      - application/json
      description: Get a list of all Permissions
      operationId: list-all-Permissions
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Permissions
          schema:
            $ref: '#/definitions/response.Response'
      summary: List all Permissions
      tags:
      - Permission
    post:
      consumes:
      - application/json
      description: Create a new Permission with the provided details
      operationId: create-Permission
      parameters:
      - description: Permission data
        in: body
        name: Permission
        required: true
        schema:
          $ref: '#/definitions/dto.PermissionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created Permission
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create a Permission
      tags:
      - Permission
  /permission/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Permission by ID
      operationId: delete-Permission-by-id
      parameters:
      - description: Permission ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted Permission
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete a Permission
      tags:
      - Permission
    get:
      consumes:
      - application/json
      description: Get a Permission by ID
      operationId: get-Permission-by-id
      parameters:
      - description: Permission ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get a Permission
      tags:
      - Permission
    patch:
      consumes:
      - application/json
      description: Update a Permission by ID
      operationId: update-Permission-by-id
      parameters:
      - description: Permission ID
        in: path
        name: id
        required: true
        type: integer
      - description: Permission data
        in: body
        name: Permission
        required: true
        schema:
          $ref: '#/definitions/dto.PermissionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated Permission
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update a Permission
      tags:
      - Permission
  /role:
    get:
      consumes:
      - application/json
      description: Get a list of all Roles
      operationId: list-all-Roles
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved Roles
          schema:
            $ref: '#/definitions/response.Response'
      summary: List all Roles
      tags:
      - Role
    post:
      consumes:
      - application/json
      description: Create a new Role with the provided details
      operationId: create-Role
      parameters:
      - description: Role data
        in: body
        name: Role
        required: true
        schema:
          $ref: '#/definitions/dto.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created Role
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create a Role
      tags:
      - Role
  /role/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Role by ID
      operationId: delete-Role-by-id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted Role
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete a Role
      tags:
      - Role
    get:
      consumes:
      - application/json
      description: Get a Role by ID
      operationId: get-Role-by-id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      security:
      - BearerAuth: []
      summary: Get a Role
      tags:
      - Role
    patch:
      consumes:
      - application/json
      description: Update a Role by ID
      operationId: update-Role-by-id
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: integer
      - description: Role data
        in: body
        name: Role
        required: true
        schema:
          $ref: '#/definitions/dto.RoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully updated Role
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update a Role
      tags:
      - Role
swagger: "2.0"
