# Configuration vars for cmd/app
[app]
env = "dev"                # dev | stage | prod
name = "Go Vue Admin"
address = ":5500"
idle_timeout = 5           # As seconds
shutdown_timeout = 10      # As seconds
print_routes = true
production = false

[api.web]
enable = true
address = ":5500"
base_path = "/web/v1"

[api.admin]
enable = true
address = ":5501"
base_path = "/admin/v1"

[api.bot]
enable = true
address = ":5502"
base_path = "/bot/v1"

[app.tls]
auto = false
enable = false
cert_file = "./storage/selfsigned.crt"
key_file = "./storage/selfsigned.key"

[db.mysql]
#dns = # <username>:<password>@tcp(<host>:<port>)/<dbname>
dsn = "root:password@tcp(localhost:3336)/gva"

[db.redis]
address = "localhost:6663"
password = "password"

[seed]
enable = true

[seed.super_admin]
username = "admin"
password = "123456"

[logger]
time_format = "" # https://pkg.go.dev/time#pkg-constants
level = 0        # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.monitor]
enable = true
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = true
max = 20
expiration_seconds = 60

[middleware.swagger]
enable = true
path = "/docs"
host = "localhost:4000"

[jwt]
secret = "jwt_secret"

[password]
hash_cost = "10"
