-- Create "departments" table
CREATE TABLE `departments` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `is_enable` bool NOT NULL DEFAULT 1, `name_id` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `parent_id` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `department_deleted_at` (`deleted_at`), UNIQUE INDEX `department_name_id_deleted_at` (`name_id`, `deleted_at`), INDEX `departments_departments_children` (`parent_id`), CONSTRAINT `departments_departments_children` FOREIGN KEY (`parent_id`) REFERENCES `departments` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "regions" table
CREATE TABLE `regions` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `is_enable` bool NOT NULL DEFAULT 1, `name_id` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `type` enum('continent','country','city','street','any') NOT NULL, `parent_id` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `region_deleted_at` (`deleted_at`), UNIQUE INDEX `region_name_id_deleted_at` (`name_id`, `deleted_at`), INDEX `regions_regions_children` (`parent_id`), CONSTRAINT `regions_regions_children` FOREIGN KEY (`parent_id`) REFERENCES `regions` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "todos" table
CREATE TABLE `todos` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), INDEX `todo_deleted_at` (`deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "admins" table
CREATE TABLE `admins` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `is_enable` bool NOT NULL DEFAULT 1, `deleted_at` bigint NOT NULL DEFAULT 0, `username` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `whitelist_ips` json NOT NULL, `display_name` varchar(255) NULL, `department_id` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `admin_deleted_at` (`deleted_at`), UNIQUE INDEX `admin_username_deleted_at` (`username`, `deleted_at`), INDEX `admins_departments_members` (`department_id`), UNIQUE INDEX `username` (`username`), CONSTRAINT `admins_departments_members` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "roles" table
CREATE TABLE `roles` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `is_enable` bool NOT NULL DEFAULT 1, `deleted_at` bigint NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, `description` varchar(255) NOT NULL, `order` bigint NOT NULL, `is_changeable` bool NOT NULL, PRIMARY KEY (`id`), INDEX `role_deleted_at` (`deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "admin_roles" table
CREATE TABLE `admin_roles` (`admin_id` varchar(255) NOT NULL, `role_id` varchar(255) NOT NULL, PRIMARY KEY (`admin_id`, `role_id`), INDEX `admin_roles_role_id` (`role_id`), CONSTRAINT `admin_roles_admin_id` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `admin_roles_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "permissions" table
CREATE TABLE `permissions` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `group` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `key` varchar(255) NOT NULL, `type` enum('dynamic','static') NULL DEFAULT "dynamic", `order` bigint NULL DEFAULT 0, PRIMARY KEY (`id`)) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "role_permissions" table
CREATE TABLE `role_permissions` (`role_id` varchar(255) NOT NULL, `permission_id` varchar(255) NOT NULL, PRIMARY KEY (`role_id`, `permission_id`), INDEX `role_permissions_permission_id` (`permission_id`), CONSTRAINT `role_permissions_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `role_permissions_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "menus" table
CREATE TABLE `menus` (`id` varchar(255) NOT NULL, `created_at` timestamp NOT NULL, `updated_at` timestamp NOT NULL, `is_enable` bool NOT NULL DEFAULT 1, `deleted_at` bigint NOT NULL DEFAULT 0, `path` varchar(255) NOT NULL, `component` varchar(255) NOT NULL, `redirect` varchar(255) NULL, `name` varchar(255) NOT NULL, `order` bigint NULL DEFAULT 0, `type` enum('cata_log','menu','button','external_link') NOT NULL DEFAULT "cata_log", `meta` json NOT NULL, `parent_id` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `menu_deleted_at` (`deleted_at`), UNIQUE INDEX `menu_path_parent_id_type_deleted_at` (`path`, `parent_id`, `type`, `deleted_at`), INDEX `menus_menus_children` (`parent_id`), CONSTRAINT `menus_menus_children` FOREIGN KEY (`parent_id`) REFERENCES `menus` (`id`) ON UPDATE NO ACTION ON DELETE SET NULL) CHARSET utf8mb4 COLLATE utf8mb4_bin;
-- Create "role_routes" table
CREATE TABLE `role_routes` (`role_id` varchar(255) NOT NULL, `menu_id` varchar(255) NOT NULL, PRIMARY KEY (`role_id`, `menu_id`), INDEX `role_routes_menu_id` (`menu_id`), CONSTRAINT `role_routes_menu_id` FOREIGN KEY (`menu_id`) REFERENCES `menus` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT `role_routes_role_id` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE) CHARSET utf8mb4 COLLATE utf8mb4_bin;
