version: "3.8"

services:
  lottery-admin:
    restart: always
    build:
      context: .
      dockerfile: ./build/Dockerfile
    environment:
      VITE_APP_TITLE: GVA
      VITE_APP_NAMESPACE: lottery-data
      VITE_PORT: 3000
      VITE_BASE: /
      VITE_GLOB_API_URL: http://localhost:8080/admin/v1
      VITE_COMPRESS: none
      VITE_PWA: false
      VITE_ROUTER_HISTORY: hash
      VITE_DEVTOOLS: false
      VITE_INJECT_APP_LOADING: true
      VITE_VISUALIZER: false
    networks:
      - webnet
    labels:
      - "com.lottery_data.description=Lottery Admin"
    ports:
      - "3000:3000"

networks:
  webnet:
    driver: bridge
