version: "3.8"

networks:
  app:
    driver: bridge

services:
  mysql:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: gva
        MYSQL_USER: user
        MYSQL_PASSWORD: user_password
      volumes:
      - mysql:/var/lib/mysql
      networks:
        - app
      ports:
        - "3306:3306"

  example:
    build:
      context: .
      dockerfile: build/Dockerfile${CUSTOM}
    volumes:
      - .:/app
    networks:
      - app
    ports:
      - 4000:4000
volumes:
  mysql: 