version: "3.8"

networks:
  app:
    driver: bridge

volumes:
  web-data:
  admin-data:
  bot-data:
  mysql-data:
  redis-data:
  grafana-data:
  prom-data:

services:
  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    networks:
      - app
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./etc/grafana/:/etc/grafana/"
    env_file:
      - ./etc/grafana/grafana.env

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    networks:
      - app
    volumes:
      - ./etc/alertmanager/:/etc/alertmanager/
    env_file:
      - ./etc/alertmanager/alertmanager.env
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  prometheus:
    image: prom/prometheus:v2.35.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    networks:
      - app
    volumes:
      - "./etc/prometheus/:/etc/prometheus/"
      - "prom-data:/prometheus"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    restart: always

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - app
    depends_on:
      - prometheus

  cortex:
    image: cortexproject/cortex:v0.1.0
    #image: ubuntu/cortex:latest
    ports:
      - "9009:9009"
    networks:
      - app
    volumes:
      - "./etc/cortex/:/etc/cortex"
    command: "-config.file=/etc/cortex/single-process-config.yaml"
    depends_on:
      - prometheus

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    depends_on: ["gva-redis"]
    ports:
      - 9121:9121
    restart: always
    volumes:
      - "./etc/redis_exporter/:/etc/redis_exporter"
    env_file:
      - ./etc/redis_exporter/redis_exporter.env
    networks:
      - app

  mysqld-exporter:
    image: prom/mysqld-exporter:main
    user: root
    networks:
      - app
    ports:
      - "9104:9104"
    volumes:
      - "./etc/mysqld_exporter/.my.cnf:/.my.cnf"
    env_file:
      - ./etc/mysqld_exporter/mysqld_exporter.env
    environment:
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - gva-mysql
