version: "3.8"

networks:
  app:
    driver: bridge

volumes:
  prom-data:

services:
  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    networks:
      - app
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./etc/grafana/provisioning/:/etc/grafana/provisioning/"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    networks:
      - app
    volumes:
      - ./etc/alertmanager/:/etc/alertmanager/
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  prometheus:
    image: prom/prometheus:v2.35.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 9090:9090
    networks:
      - app
    volumes:
      - "./etc/alert.rules.yml:/etc/prometheus/rules.yml"
      - "./etc/prometheus/:/etc/prometheus/"
      - "prom-data:/prometheus"

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    restart: always

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
    networks:
      - app
    depends_on:
      - prometheus

  cortex:
    image: cortexproject/cortex:v1.17.1
    #image: ubuntu/cortex:latest
    ports:
      - "9009:9009"
    networks:
      - app
    command: "-config.file=/etc/single-process-config.yaml"
    depends_on:
      - prometheus
    volumes:
      - "./etc/cortex/single-process-config.yaml:/etc/single-process-config.yaml"

  redis-exporter:
    image: oliver006/redis_exporter:alpine
    depends_on: ["gva-redis"]
    ports:
      - 9121:9121
    restart: always
    networks:
      - app
    environment:
      - REDIS_ADDR=${DB.REDIS.ADDRESS}
      - REDIS_PASSWORD=${DB.REDIS.PASSWORD}

  mysqld-exporter:
    image: prom/mysqld-exporter:main
    user: root
    networks:
      - app
    ports:
      - "9104:9104"
    volumes:
      - "./etc/mysqld_exporter/.my.cnf:/.my.cnf"
    environment:
      - "MYSQLD_EXPORTER_PASSWORD=${DB.MYSQL.PASSWORD}"
      - "mysqld.address=${DB.MYSQL.ADDRESS}"
      - "mysqld.username=${DB.MYSQL.USERNAME}"
      - "collect.info_schema.tablestats=true"
      - "collect.info_schema.userstats=true"
      - "collect.info_schema.query_response_time=true"
      - "collect.auto_increment.columns=true"
      - "collect.perf_schema.tableiowaits=true"
      - "collect.perf_schema.tablelocks=true"
    depends_on:
      - gva-mysql
