# Configuration vars for cmd/app
[app]
env = "dev"             # dev | stage | prod
name = "Go Vue Admin"
port = ":4000"
idle_timeout = 5        # As seconds
shutdown_timeout = 10   # As seconds
print_routes = true
production = false
host = "localhost:4000"

[app.tls]
auto = false
enable = false
cert_file = "./storage/selfsigned.crt"
key_file = "./storage/selfsigned.key"

[db.mysql]
#dns = # <username>:<password>@tcp(<host>:<port>)/<dbname>
dsn = "root:password@tcp(localhost:3306)/gva_backend?parseTime=true"

[db.redis]
enable = false
url = "rediss://foxie:foxiepw@localhost:6379"

[seed]
enable = true

[seed.super_admin]
username = "admin"
password = "123456"

[api.admin]
enable = true
base_path = "/admin/v1"

[api.bot]
enable = true
base_path = "/bot/v1"

[api.bot.scrap]
proxy = "http://admin.campaign.ss.hd1.fun:24127/api/proxy/forward"

[api.bot.scrap.game]
enable = false

[api.bot.scrap.article]
enable = false


[logger]
time_format = "" # https://pkg.go.dev/time#pkg-constants
level = 0        # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true

[middleware.compress]
enable = true
level = 1

[middleware.monitor]
enable = true
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = true
max = 20
expiration_seconds = 60

[middleware.swagger]
enable = true
path = "/docs"

[jwt]
secret = "jwt_secret"

[password]
hash_cost = "10"

[s3]
region = ""
bucket_name = ""
access_key_id = ""
secret_access_key = ""
endpoint = ""
session_token = ""

[totp]
test_code=666666

[google]
enable = false
chat_webhook_url = ""
# redis://<username>:<password>@<host>:<port>
