-- Create "admins" table
CREATE TABLE `admins` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NULL, `updated_at` datetime(3) NULL, `deleted_at` bigint unsigned NOT NULL DEFAULT 0, `password_hash` varchar(255) NULL, `status` bigint NULL DEFAULT 1, `name` varchar(255) NULL, `username` varchar(255) NULL, `ip_white_list` json NULL, `current_login_ip` varchar(255) NULL, `last_login_ip` varchar(255) NULL, `current_region` varchar(255) NULL, `last_region` varchar(255) NULL, `current_login_at` datetime(3) NULL, `last_login_at` datetime(3) NULL, `google_secret_key` varchar(255) NULL, `google_otp` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `idx_admins_deleted_at` (`deleted_at`), UNIQUE INDEX `idx_admins_username_deleted_at` (`username`, `deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "configurations" table
CREATE TABLE `configurations` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `key` varchar(255) NOT NULL, `type` varchar(255) NOT NULL, `value` json NULL, `parent_id` bigint unsigned NULL, `status` tinyint NOT NULL DEFAULT 1, `updated_at` datetime(3) NULL, `created_at` datetime(3) NOT NULL, `deleted_at` bigint unsigned NOT NULL DEFAULT 0, `description` varchar(255) NULL, `metadata` json NULL, `root_id` bigint unsigned NULL, PRIMARY KEY (`id`), INDEX `fk_configuration_parent_id` (`parent_id`), INDEX `fk_configuration_root_id` (`root_id`), UNIQUE INDEX `key` (`key`, `deleted_at`), CONSTRAINT `fk_configuration_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `configurations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `fk_configuration_root_id` FOREIGN KEY (`root_id`) REFERENCES `configurations` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "admin_roles" table
CREATE TABLE `admin_roles` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NULL, `updated_at` datetime(3) NULL, `deleted_at` bigint unsigned NOT NULL DEFAULT 0, `name` varchar(255) NULL, `status` bigint NULL DEFAULT 1, `order` int NOT NULL DEFAULT 0, `type` int NOT NULL DEFAULT 1, `name_id` varchar(30) NOT NULL, `description` varchar(255) NULL, PRIMARY KEY (`id`), INDEX `idx_admin_roles_deleted_at` (`deleted_at`), UNIQUE INDEX `idx_admin_roles_name_id_deleted_at` (`name_id`, `deleted_at`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "admin_admin_roles" table
CREATE TABLE `admin_admin_roles` (`admin_id` bigint unsigned NOT NULL, `admin_role_id` bigint unsigned NOT NULL, PRIMARY KEY (`admin_id`, `admin_role_id`), INDEX `admin_admin_roles_role` (`admin_role_id`), CONSTRAINT `admin_admin_roles_admin` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `admin_admin_roles_admin_role` FOREIGN KEY (`admin_role_id`) REFERENCES `admin_roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "permissions" table
CREATE TABLE `permissions` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NOT NULL, `group` varchar(255) NOT NULL, `scope` varchar(255) NOT NULL, `order` int NOT NULL DEFAULT 0, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`), UNIQUE INDEX `idx_uniq_permissions_scope` (`scope`)) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "admin_role_permissions" table
CREATE TABLE `admin_role_permissions` (`admin_role_id` bigint unsigned NOT NULL, `permission_id` bigint unsigned NOT NULL, PRIMARY KEY (`admin_role_id`, `permission_id`), INDEX `fk_admin_role_permissions_permission` (`permission_id`), CONSTRAINT `fk_admin_role_permissions_admin_role` FOREIGN KEY (`admin_role_id`) REFERENCES `admin_roles` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT `fk_admin_role_permissions_permission` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
-- Create "operation_logs" table
CREATE TABLE `operation_logs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT, `created_at` datetime(3) NULL, `admin_id` bigint unsigned NULL, `role_ids` json NULL, `method` varchar(7) NULL, `path` varchar(255) NULL, `scope` varchar(255) NULL, `ip` varchar(39) NULL, `data` json NULL, `code` int NULL, `error` longtext NULL, `msg` longtext NULL, `latency` int unsigned NULL, PRIMARY KEY (`id`), INDEX `fk_operation_logs_admin` (`admin_id`), CONSTRAINT `fk_operation_logs_admin` FOREIGN KEY (`admin_id`) REFERENCES `admins` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION) CHARSET utf8mb4 COLLATE utf8mb4_general_ci;
