basePath: /bot/v1
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data:
        description: The Data field contains the actual response data
      message:
        type: string
      meta:
        description: Meta provides additional information about the data, such as
          its type or kind.y.
    type: object
host: localhost:5500
info:
  contact: {}
  description: GO VUE ADMIN Boilerplate
  title: GVA bot API
  version: "1.0"
paths:
  /file/static/img/{name}:
    get:
      description: Serves files from `storage/static` directory
      operationId: serve-static-files
      parameters:
      - description: filename
        in: path
        name: name
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Serve static files
      tags:
      - File
  /file/upload-img:
    post:
      consumes:
      - multipart/form-data
      description: Upload a file
      operationId: upload-file
      parameters:
      - description: File
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
      summary: Upload a file
      tags:
      - File
  /health-check:
    get:
      operationId: health-check
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - Bearer: []
      summary: Health Check
      tags:
      - Index
  /now:
    get:
      operationId: now
      produces:
      - application/json
      responses:
        "200":
          description: format time.RFC3339
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - Bearer: []
      summary: Current Server Time
      tags:
      - Index
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
