basePath: /bot/v1
definitions:
  response.Response:
    properties:
      code:
        type: integer
      data:
        description: The Data field contains the actual response data
      message:
        type: string
      meta:
        description: Meta provides additional information about the data, such as
          its type or kind.y.
    type: object
host: localhost:4000
info:
  contact: {}
  description: GO VUE ADMIN Boilerplate
  title: GVA bot API
  version: "1.0"
paths:
  /health-check:
    get:
      operationId: health-check
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      security:
      - Bearer: []
      summary: Health Check
      tags:
      - Index
  /now:
    get:
      operationId: now
      produces:
      - application/json
      responses:
        "200":
          description: format time.RFC3339
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - Bearer: []
      summary: Current Server Time
      tags:
      - Index
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
