global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "gva-monitor"

rule_files:
  - "alert.rule.yml"

# Grafana URL: http://cortex:9009/api/prom
remote_write:
  - url: http://cortex:9009/api/prom/push

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  # Doc: https://docs.docker.com/config/daemon/prometheus/
  # Linux Workaround: https://stackoverflow.com/a/67158212/1341168
  - job_name: docker
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: "pushgateway"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: redis-exporter
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "mysql-exporter"
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ["mysqld-exporter:9104"]

  - job_name: gva-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          [
            "gva-backend-web:5500",
            "gva-backend-admin:5501",
            "gva-backend-bot:5502",
          ]
