// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/kimchhung/gva/backend/app/database/schema"
	"github.com/kimchhung/gva/backend/internal/ent/admin"
	"github.com/kimchhung/gva/backend/internal/ent/comic"
	"github.com/kimchhung/gva/backend/internal/ent/comicchapter"
	"github.com/kimchhung/gva/backend/internal/ent/comicimg"
	"github.com/kimchhung/gva/backend/internal/ent/genre"
	"github.com/kimchhung/gva/backend/internal/ent/permission"
	"github.com/kimchhung/gva/backend/internal/ent/role"
	"github.com/kimchhung/gva/backend/internal/ent/route"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminMixin := schema.Admin{}.Mixin()
	adminMixinHooks2 := adminMixin[2].Hooks()
	admin.Hooks[0] = adminMixinHooks2[0]
	adminMixinFields0 := adminMixin[0].Fields()
	_ = adminMixinFields0
	adminMixinFields1 := adminMixin[1].Fields()
	_ = adminMixinFields1
	adminMixinFields2 := adminMixin[2].Fields()
	_ = adminMixinFields2
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminMixinFields0[0].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminMixinFields0[1].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminDescIsEnable is the schema descriptor for is_enable field.
	adminDescIsEnable := adminMixinFields1[0].Descriptor()
	// admin.DefaultIsEnable holds the default value on creation for the is_enable field.
	admin.DefaultIsEnable = adminDescIsEnable.Default.(bool)
	// adminDescDeletedAt is the schema descriptor for deleted_at field.
	adminDescDeletedAt := adminMixinFields2[0].Descriptor()
	// admin.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	admin.DefaultDeletedAt = adminDescDeletedAt.Default.(int)
	comicMixin := schema.Comic{}.Mixin()
	comicMixinFields1 := comicMixin[1].Fields()
	_ = comicMixinFields1
	comicFields := schema.Comic{}.Fields()
	_ = comicFields
	// comicDescCreatedAt is the schema descriptor for created_at field.
	comicDescCreatedAt := comicMixinFields1[0].Descriptor()
	// comic.DefaultCreatedAt holds the default value on creation for the created_at field.
	comic.DefaultCreatedAt = comicDescCreatedAt.Default.(func() time.Time)
	// comicDescUpdatedAt is the schema descriptor for updated_at field.
	comicDescUpdatedAt := comicMixinFields1[1].Descriptor()
	// comic.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comic.DefaultUpdatedAt = comicDescUpdatedAt.Default.(func() time.Time)
	// comic.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comic.UpdateDefaultUpdatedAt = comicDescUpdatedAt.UpdateDefault.(func() time.Time)
	// comicDescIsTranslateCompleted is the schema descriptor for isTranslateCompleted field.
	comicDescIsTranslateCompleted := comicFields[5].Descriptor()
	// comic.DefaultIsTranslateCompleted holds the default value on creation for the isTranslateCompleted field.
	comic.DefaultIsTranslateCompleted = comicDescIsTranslateCompleted.Default.(bool)
	// comicDescUpCount is the schema descriptor for up_count field.
	comicDescUpCount := comicFields[6].Descriptor()
	// comic.DefaultUpCount holds the default value on creation for the up_count field.
	comic.DefaultUpCount = comicDescUpCount.Default.(uint)
	comicchapterMixin := schema.ComicChapter{}.Mixin()
	comicchapterMixinFields1 := comicchapterMixin[1].Fields()
	_ = comicchapterMixinFields1
	comicchapterFields := schema.ComicChapter{}.Fields()
	_ = comicchapterFields
	// comicchapterDescCreatedAt is the schema descriptor for created_at field.
	comicchapterDescCreatedAt := comicchapterMixinFields1[0].Descriptor()
	// comicchapter.DefaultCreatedAt holds the default value on creation for the created_at field.
	comicchapter.DefaultCreatedAt = comicchapterDescCreatedAt.Default.(func() time.Time)
	// comicchapterDescUpdatedAt is the schema descriptor for updated_at field.
	comicchapterDescUpdatedAt := comicchapterMixinFields1[1].Descriptor()
	// comicchapter.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comicchapter.DefaultUpdatedAt = comicchapterDescUpdatedAt.Default.(func() time.Time)
	// comicchapter.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comicchapter.UpdateDefaultUpdatedAt = comicchapterDescUpdatedAt.UpdateDefault.(func() time.Time)
	// comicchapterDescUpCount is the schema descriptor for up_count field.
	comicchapterDescUpCount := comicchapterFields[4].Descriptor()
	// comicchapter.DefaultUpCount holds the default value on creation for the up_count field.
	comicchapter.DefaultUpCount = comicchapterDescUpCount.Default.(uint)
	// comicchapterDescDownCount is the schema descriptor for down_count field.
	comicchapterDescDownCount := comicchapterFields[5].Descriptor()
	// comicchapter.DefaultDownCount holds the default value on creation for the down_count field.
	comicchapter.DefaultDownCount = comicchapterDescDownCount.Default.(uint)
	// comicchapterDescIsLastChapter is the schema descriptor for is_last_chapter field.
	comicchapterDescIsLastChapter := comicchapterFields[6].Descriptor()
	// comicchapter.DefaultIsLastChapter holds the default value on creation for the is_last_chapter field.
	comicchapter.DefaultIsLastChapter = comicchapterDescIsLastChapter.Default.(bool)
	comicimgMixin := schema.ComicImg{}.Mixin()
	comicimgMixinFields1 := comicimgMixin[1].Fields()
	_ = comicimgMixinFields1
	comicimgFields := schema.ComicImg{}.Fields()
	_ = comicimgFields
	// comicimgDescCreatedAt is the schema descriptor for created_at field.
	comicimgDescCreatedAt := comicimgMixinFields1[0].Descriptor()
	// comicimg.DefaultCreatedAt holds the default value on creation for the created_at field.
	comicimg.DefaultCreatedAt = comicimgDescCreatedAt.Default.(func() time.Time)
	// comicimgDescUpdatedAt is the schema descriptor for updated_at field.
	comicimgDescUpdatedAt := comicimgMixinFields1[1].Descriptor()
	// comicimg.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comicimg.DefaultUpdatedAt = comicimgDescUpdatedAt.Default.(func() time.Time)
	// comicimg.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comicimg.UpdateDefaultUpdatedAt = comicimgDescUpdatedAt.UpdateDefault.(func() time.Time)
	genreMixin := schema.Genre{}.Mixin()
	genreMixinFields1 := genreMixin[1].Fields()
	_ = genreMixinFields1
	genreFields := schema.Genre{}.Fields()
	_ = genreFields
	// genreDescCreatedAt is the schema descriptor for created_at field.
	genreDescCreatedAt := genreMixinFields1[0].Descriptor()
	// genre.DefaultCreatedAt holds the default value on creation for the created_at field.
	genre.DefaultCreatedAt = genreDescCreatedAt.Default.(func() time.Time)
	// genreDescUpdatedAt is the schema descriptor for updated_at field.
	genreDescUpdatedAt := genreMixinFields1[1].Descriptor()
	// genre.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	genre.DefaultUpdatedAt = genreDescUpdatedAt.Default.(func() time.Time)
	// genre.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	genre.UpdateDefaultUpdatedAt = genreDescUpdatedAt.UpdateDefault.(func() time.Time)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields0[0].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields0[1].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	roleMixin := schema.Role{}.Mixin()
	roleMixinHooks2 := roleMixin[2].Hooks()
	role.Hooks[0] = roleMixinHooks2[0]
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleMixinFields2 := roleMixin[2].Fields()
	_ = roleMixinFields2
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescIsEnable is the schema descriptor for is_enable field.
	roleDescIsEnable := roleMixinFields1[0].Descriptor()
	// role.DefaultIsEnable holds the default value on creation for the is_enable field.
	role.DefaultIsEnable = roleDescIsEnable.Default.(bool)
	// roleDescDeletedAt is the schema descriptor for deleted_at field.
	roleDescDeletedAt := roleMixinFields2[0].Descriptor()
	// role.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	role.DefaultDeletedAt = roleDescDeletedAt.Default.(int)
	routeMixin := schema.Route{}.Mixin()
	routeMixinHooks2 := routeMixin[2].Hooks()
	route.Hooks[0] = routeMixinHooks2[0]
	routeMixinFields0 := routeMixin[0].Fields()
	_ = routeMixinFields0
	routeMixinFields1 := routeMixin[1].Fields()
	_ = routeMixinFields1
	routeMixinFields2 := routeMixin[2].Fields()
	_ = routeMixinFields2
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescCreatedAt is the schema descriptor for created_at field.
	routeDescCreatedAt := routeMixinFields0[0].Descriptor()
	// route.DefaultCreatedAt holds the default value on creation for the created_at field.
	route.DefaultCreatedAt = routeDescCreatedAt.Default.(func() time.Time)
	// routeDescUpdatedAt is the schema descriptor for updated_at field.
	routeDescUpdatedAt := routeMixinFields0[1].Descriptor()
	// route.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	route.DefaultUpdatedAt = routeDescUpdatedAt.Default.(func() time.Time)
	// route.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	route.UpdateDefaultUpdatedAt = routeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// routeDescIsEnable is the schema descriptor for is_enable field.
	routeDescIsEnable := routeMixinFields1[0].Descriptor()
	// route.DefaultIsEnable holds the default value on creation for the is_enable field.
	route.DefaultIsEnable = routeDescIsEnable.Default.(bool)
	// routeDescDeletedAt is the schema descriptor for deleted_at field.
	routeDescDeletedAt := routeMixinFields2[0].Descriptor()
	// route.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	route.DefaultDeletedAt = routeDescDeletedAt.Default.(int)
}

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
