// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/gva/app/database/schema"
	"github.com/gva/app/database/schema/xid"
	"github.com/gva/internal/ent/admin"
	"github.com/gva/internal/ent/department"
	"github.com/gva/internal/ent/menu"
	"github.com/gva/internal/ent/mytodo"
	"github.com/gva/internal/ent/mytodo1"
	"github.com/gva/internal/ent/permission"
	"github.com/gva/internal/ent/region"
	"github.com/gva/internal/ent/role"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminMixin := schema.Admin{}.Mixin()
	adminMixinHooks3 := adminMixin[3].Hooks()
	admin.Hooks[0] = adminMixinHooks3[0]
	adminMixinInters3 := adminMixin[3].Interceptors()
	admin.Interceptors[0] = adminMixinInters3[0]
	adminMixinFields0 := adminMixin[0].Fields()
	_ = adminMixinFields0
	adminMixinFields1 := adminMixin[1].Fields()
	_ = adminMixinFields1
	adminMixinFields2 := adminMixin[2].Fields()
	_ = adminMixinFields2
	adminMixinFields3 := adminMixin[3].Fields()
	_ = adminMixinFields3
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminMixinFields1[0].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminMixinFields1[1].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminDescIsEnable is the schema descriptor for is_enable field.
	adminDescIsEnable := adminMixinFields2[0].Descriptor()
	// admin.DefaultIsEnable holds the default value on creation for the is_enable field.
	admin.DefaultIsEnable = adminDescIsEnable.Default.(bool)
	// adminDescDeletedAt is the schema descriptor for deleted_at field.
	adminDescDeletedAt := adminMixinFields3[0].Descriptor()
	// admin.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	admin.DefaultDeletedAt = adminDescDeletedAt.Default.(int)
	// adminDescID is the schema descriptor for id field.
	adminDescID := adminMixinFields0[0].Descriptor()
	// admin.DefaultID holds the default value on creation for the id field.
	admin.DefaultID = adminDescID.Default.(func() xid.ID)
	departmentMixin := schema.Department{}.Mixin()
	departmentMixinHooks2 := departmentMixin[2].Hooks()
	department.Hooks[0] = departmentMixinHooks2[0]
	departmentMixinInters2 := departmentMixin[2].Interceptors()
	department.Interceptors[0] = departmentMixinInters2[0]
	departmentMixinFields0 := departmentMixin[0].Fields()
	_ = departmentMixinFields0
	departmentMixinFields1 := departmentMixin[1].Fields()
	_ = departmentMixinFields1
	departmentMixinFields2 := departmentMixin[2].Fields()
	_ = departmentMixinFields2
	departmentMixinFields3 := departmentMixin[3].Fields()
	_ = departmentMixinFields3
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescCreatedAt is the schema descriptor for created_at field.
	departmentDescCreatedAt := departmentMixinFields1[0].Descriptor()
	// department.DefaultCreatedAt holds the default value on creation for the created_at field.
	department.DefaultCreatedAt = departmentDescCreatedAt.Default.(func() time.Time)
	// departmentDescUpdatedAt is the schema descriptor for updated_at field.
	departmentDescUpdatedAt := departmentMixinFields1[1].Descriptor()
	// department.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	department.DefaultUpdatedAt = departmentDescUpdatedAt.Default.(func() time.Time)
	// department.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	department.UpdateDefaultUpdatedAt = departmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// departmentDescDeletedAt is the schema descriptor for deleted_at field.
	departmentDescDeletedAt := departmentMixinFields2[0].Descriptor()
	// department.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	department.DefaultDeletedAt = departmentDescDeletedAt.Default.(int)
	// departmentDescIsEnable is the schema descriptor for is_enable field.
	departmentDescIsEnable := departmentMixinFields3[0].Descriptor()
	// department.DefaultIsEnable holds the default value on creation for the is_enable field.
	department.DefaultIsEnable = departmentDescIsEnable.Default.(bool)
	// departmentDescID is the schema descriptor for id field.
	departmentDescID := departmentMixinFields0[0].Descriptor()
	// department.DefaultID holds the default value on creation for the id field.
	department.DefaultID = departmentDescID.Default.(func() xid.ID)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinHooks3 := menuMixin[3].Hooks()
	menu.Hooks[0] = menuMixinHooks3[0]
	menuMixinInters3 := menuMixin[3].Interceptors()
	menu.Interceptors[0] = menuMixinInters3[0]
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuMixinFields1 := menuMixin[1].Fields()
	_ = menuMixinFields1
	menuMixinFields2 := menuMixin[2].Fields()
	_ = menuMixinFields2
	menuMixinFields3 := menuMixin[3].Fields()
	_ = menuMixinFields3
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreatedAt is the schema descriptor for created_at field.
	menuDescCreatedAt := menuMixinFields1[0].Descriptor()
	// menu.DefaultCreatedAt holds the default value on creation for the created_at field.
	menu.DefaultCreatedAt = menuDescCreatedAt.Default.(func() time.Time)
	// menuDescUpdatedAt is the schema descriptor for updated_at field.
	menuDescUpdatedAt := menuMixinFields1[1].Descriptor()
	// menu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	menu.DefaultUpdatedAt = menuDescUpdatedAt.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	menu.UpdateDefaultUpdatedAt = menuDescUpdatedAt.UpdateDefault.(func() time.Time)
	// menuDescIsEnable is the schema descriptor for is_enable field.
	menuDescIsEnable := menuMixinFields2[0].Descriptor()
	// menu.DefaultIsEnable holds the default value on creation for the is_enable field.
	menu.DefaultIsEnable = menuDescIsEnable.Default.(bool)
	// menuDescDeletedAt is the schema descriptor for deleted_at field.
	menuDescDeletedAt := menuMixinFields3[0].Descriptor()
	// menu.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	menu.DefaultDeletedAt = menuDescDeletedAt.Default.(int)
	// menuDescOrder is the schema descriptor for order field.
	menuDescOrder := menuFields[5].Descriptor()
	// menu.DefaultOrder holds the default value on creation for the order field.
	menu.DefaultOrder = menuDescOrder.Default.(int)
	// menuDescID is the schema descriptor for id field.
	menuDescID := menuMixinFields0[0].Descriptor()
	// menu.DefaultID holds the default value on creation for the id field.
	menu.DefaultID = menuDescID.Default.(func() xid.ID)
	mytodoMixin := schema.MyTodo{}.Mixin()
	mytodoMixinHooks2 := mytodoMixin[2].Hooks()
	mytodo.Hooks[0] = mytodoMixinHooks2[0]
	mytodoMixinInters2 := mytodoMixin[2].Interceptors()
	mytodo.Interceptors[0] = mytodoMixinInters2[0]
	mytodoMixinFields0 := mytodoMixin[0].Fields()
	_ = mytodoMixinFields0
	mytodoMixinFields1 := mytodoMixin[1].Fields()
	_ = mytodoMixinFields1
	mytodoMixinFields2 := mytodoMixin[2].Fields()
	_ = mytodoMixinFields2
	mytodoFields := schema.MyTodo{}.Fields()
	_ = mytodoFields
	// mytodoDescCreatedAt is the schema descriptor for created_at field.
	mytodoDescCreatedAt := mytodoMixinFields1[0].Descriptor()
	// mytodo.DefaultCreatedAt holds the default value on creation for the created_at field.
	mytodo.DefaultCreatedAt = mytodoDescCreatedAt.Default.(func() time.Time)
	// mytodoDescUpdatedAt is the schema descriptor for updated_at field.
	mytodoDescUpdatedAt := mytodoMixinFields1[1].Descriptor()
	// mytodo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mytodo.DefaultUpdatedAt = mytodoDescUpdatedAt.Default.(func() time.Time)
	// mytodo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mytodo.UpdateDefaultUpdatedAt = mytodoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// mytodoDescDeletedAt is the schema descriptor for deleted_at field.
	mytodoDescDeletedAt := mytodoMixinFields2[0].Descriptor()
	// mytodo.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	mytodo.DefaultDeletedAt = mytodoDescDeletedAt.Default.(int)
	// mytodoDescID is the schema descriptor for id field.
	mytodoDescID := mytodoMixinFields0[0].Descriptor()
	// mytodo.DefaultID holds the default value on creation for the id field.
	mytodo.DefaultID = mytodoDescID.Default.(func() xid.ID)
	mytodo1Mixin := schema.MyTodo1{}.Mixin()
	mytodo1MixinHooks2 := mytodo1Mixin[2].Hooks()
	mytodo1.Hooks[0] = mytodo1MixinHooks2[0]
	mytodo1MixinInters2 := mytodo1Mixin[2].Interceptors()
	mytodo1.Interceptors[0] = mytodo1MixinInters2[0]
	mytodo1MixinFields0 := mytodo1Mixin[0].Fields()
	_ = mytodo1MixinFields0
	mytodo1MixinFields1 := mytodo1Mixin[1].Fields()
	_ = mytodo1MixinFields1
	mytodo1MixinFields2 := mytodo1Mixin[2].Fields()
	_ = mytodo1MixinFields2
	mytodo1Fields := schema.MyTodo1{}.Fields()
	_ = mytodo1Fields
	// mytodo1DescCreatedAt is the schema descriptor for created_at field.
	mytodo1DescCreatedAt := mytodo1MixinFields1[0].Descriptor()
	// mytodo1.DefaultCreatedAt holds the default value on creation for the created_at field.
	mytodo1.DefaultCreatedAt = mytodo1DescCreatedAt.Default.(func() time.Time)
	// mytodo1DescUpdatedAt is the schema descriptor for updated_at field.
	mytodo1DescUpdatedAt := mytodo1MixinFields1[1].Descriptor()
	// mytodo1.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	mytodo1.DefaultUpdatedAt = mytodo1DescUpdatedAt.Default.(func() time.Time)
	// mytodo1.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	mytodo1.UpdateDefaultUpdatedAt = mytodo1DescUpdatedAt.UpdateDefault.(func() time.Time)
	// mytodo1DescDeletedAt is the schema descriptor for deleted_at field.
	mytodo1DescDeletedAt := mytodo1MixinFields2[0].Descriptor()
	// mytodo1.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	mytodo1.DefaultDeletedAt = mytodo1DescDeletedAt.Default.(int)
	// mytodo1DescID is the schema descriptor for id field.
	mytodo1DescID := mytodo1MixinFields0[0].Descriptor()
	// mytodo1.DefaultID holds the default value on creation for the id field.
	mytodo1.DefaultID = mytodo1DescID.Default.(func() xid.ID)
	permissionMixin := schema.Permission{}.Mixin()
	permissionMixinFields0 := permissionMixin[0].Fields()
	_ = permissionMixinFields0
	permissionMixinFields1 := permissionMixin[1].Fields()
	_ = permissionMixinFields1
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionMixinFields1[0].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() time.Time)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionMixinFields1[1].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() time.Time)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// permissionDescOrder is the schema descriptor for order field.
	permissionDescOrder := permissionFields[4].Descriptor()
	// permission.DefaultOrder holds the default value on creation for the order field.
	permission.DefaultOrder = permissionDescOrder.Default.(int)
	// permissionDescID is the schema descriptor for id field.
	permissionDescID := permissionMixinFields0[0].Descriptor()
	// permission.DefaultID holds the default value on creation for the id field.
	permission.DefaultID = permissionDescID.Default.(func() xid.ID)
	regionMixin := schema.Region{}.Mixin()
	regionMixinHooks2 := regionMixin[2].Hooks()
	region.Hooks[0] = regionMixinHooks2[0]
	regionMixinInters2 := regionMixin[2].Interceptors()
	region.Interceptors[0] = regionMixinInters2[0]
	regionMixinFields0 := regionMixin[0].Fields()
	_ = regionMixinFields0
	regionMixinFields1 := regionMixin[1].Fields()
	_ = regionMixinFields1
	regionMixinFields2 := regionMixin[2].Fields()
	_ = regionMixinFields2
	regionMixinFields3 := regionMixin[3].Fields()
	_ = regionMixinFields3
	regionFields := schema.Region{}.Fields()
	_ = regionFields
	// regionDescCreatedAt is the schema descriptor for created_at field.
	regionDescCreatedAt := regionMixinFields1[0].Descriptor()
	// region.DefaultCreatedAt holds the default value on creation for the created_at field.
	region.DefaultCreatedAt = regionDescCreatedAt.Default.(func() time.Time)
	// regionDescUpdatedAt is the schema descriptor for updated_at field.
	regionDescUpdatedAt := regionMixinFields1[1].Descriptor()
	// region.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	region.DefaultUpdatedAt = regionDescUpdatedAt.Default.(func() time.Time)
	// region.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	region.UpdateDefaultUpdatedAt = regionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// regionDescDeletedAt is the schema descriptor for deleted_at field.
	regionDescDeletedAt := regionMixinFields2[0].Descriptor()
	// region.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	region.DefaultDeletedAt = regionDescDeletedAt.Default.(int)
	// regionDescIsEnable is the schema descriptor for is_enable field.
	regionDescIsEnable := regionMixinFields3[0].Descriptor()
	// region.DefaultIsEnable holds the default value on creation for the is_enable field.
	region.DefaultIsEnable = regionDescIsEnable.Default.(bool)
	// regionDescID is the schema descriptor for id field.
	regionDescID := regionMixinFields0[0].Descriptor()
	// region.DefaultID holds the default value on creation for the id field.
	region.DefaultID = regionDescID.Default.(func() xid.ID)
	roleMixin := schema.Role{}.Mixin()
	roleMixinHooks3 := roleMixin[3].Hooks()
	role.Hooks[0] = roleMixinHooks3[0]
	roleMixinInters3 := roleMixin[3].Interceptors()
	role.Interceptors[0] = roleMixinInters3[0]
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleMixinFields2 := roleMixin[2].Fields()
	_ = roleMixinFields2
	roleMixinFields3 := roleMixin[3].Fields()
	_ = roleMixinFields3
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields1[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields1[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescIsEnable is the schema descriptor for is_enable field.
	roleDescIsEnable := roleMixinFields2[0].Descriptor()
	// role.DefaultIsEnable holds the default value on creation for the is_enable field.
	role.DefaultIsEnable = roleDescIsEnable.Default.(bool)
	// roleDescDeletedAt is the schema descriptor for deleted_at field.
	roleDescDeletedAt := roleMixinFields3[0].Descriptor()
	// role.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	role.DefaultDeletedAt = roleDescDeletedAt.Default.(int)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleMixinFields0[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() xid.ID)
}

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
