// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/kimchhung/gva/extra/app/database/schema"
	"github.com/kimchhung/gva/extra/internal/ent/admin"
	"github.com/kimchhung/gva/extra/internal/ent/role"
	"github.com/kimchhung/gva/extra/internal/ent/route"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminMixin := schema.Admin{}.Mixin()
	adminMixinHooks2 := adminMixin[2].Hooks()
	admin.Hooks[0] = adminMixinHooks2[0]
	adminMixinInters2 := adminMixin[2].Interceptors()
	admin.Interceptors[0] = adminMixinInters2[0]
	adminMixinFields0 := adminMixin[0].Fields()
	_ = adminMixinFields0
	adminMixinFields1 := adminMixin[1].Fields()
	_ = adminMixinFields1
	adminMixinFields2 := adminMixin[2].Fields()
	_ = adminMixinFields2
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescCreatedAt is the schema descriptor for created_at field.
	adminDescCreatedAt := adminMixinFields0[0].Descriptor()
	// admin.DefaultCreatedAt holds the default value on creation for the created_at field.
	admin.DefaultCreatedAt = adminDescCreatedAt.Default.(func() time.Time)
	// adminDescUpdatedAt is the schema descriptor for updated_at field.
	adminDescUpdatedAt := adminMixinFields0[1].Descriptor()
	// admin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	admin.DefaultUpdatedAt = adminDescUpdatedAt.Default.(func() time.Time)
	// admin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	admin.UpdateDefaultUpdatedAt = adminDescUpdatedAt.UpdateDefault.(func() time.Time)
	// adminDescIsEnable is the schema descriptor for is_enable field.
	adminDescIsEnable := adminMixinFields1[0].Descriptor()
	// admin.DefaultIsEnable holds the default value on creation for the is_enable field.
	admin.DefaultIsEnable = adminDescIsEnable.Default.(bool)
	// adminDescDeletedAt is the schema descriptor for deleted_at field.
	adminDescDeletedAt := adminMixinFields2[0].Descriptor()
	// admin.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	admin.DefaultDeletedAt = adminDescDeletedAt.Default.(int)
	roleMixin := schema.Role{}.Mixin()
	roleMixinHooks2 := roleMixin[2].Hooks()
	role.Hooks[0] = roleMixinHooks2[0]
	roleMixinInters2 := roleMixin[2].Interceptors()
	role.Interceptors[0] = roleMixinInters2[0]
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleMixinFields1 := roleMixin[1].Fields()
	_ = roleMixinFields1
	roleMixinFields2 := roleMixin[2].Fields()
	_ = roleMixinFields2
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescIsEnable is the schema descriptor for is_enable field.
	roleDescIsEnable := roleMixinFields1[0].Descriptor()
	// role.DefaultIsEnable holds the default value on creation for the is_enable field.
	role.DefaultIsEnable = roleDescIsEnable.Default.(bool)
	// roleDescDeletedAt is the schema descriptor for deleted_at field.
	roleDescDeletedAt := roleMixinFields2[0].Descriptor()
	// role.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	role.DefaultDeletedAt = roleDescDeletedAt.Default.(int)
	routeMixin := schema.Route{}.Mixin()
	routeMixinHooks2 := routeMixin[2].Hooks()
	route.Hooks[0] = routeMixinHooks2[0]
	routeMixinInters2 := routeMixin[2].Interceptors()
	route.Interceptors[0] = routeMixinInters2[0]
	routeMixinFields0 := routeMixin[0].Fields()
	_ = routeMixinFields0
	routeMixinFields1 := routeMixin[1].Fields()
	_ = routeMixinFields1
	routeMixinFields2 := routeMixin[2].Fields()
	_ = routeMixinFields2
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescCreatedAt is the schema descriptor for created_at field.
	routeDescCreatedAt := routeMixinFields0[0].Descriptor()
	// route.DefaultCreatedAt holds the default value on creation for the created_at field.
	route.DefaultCreatedAt = routeDescCreatedAt.Default.(func() time.Time)
	// routeDescUpdatedAt is the schema descriptor for updated_at field.
	routeDescUpdatedAt := routeMixinFields0[1].Descriptor()
	// route.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	route.DefaultUpdatedAt = routeDescUpdatedAt.Default.(func() time.Time)
	// route.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	route.UpdateDefaultUpdatedAt = routeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// routeDescIsEnable is the schema descriptor for is_enable field.
	routeDescIsEnable := routeMixinFields1[0].Descriptor()
	// route.DefaultIsEnable holds the default value on creation for the is_enable field.
	route.DefaultIsEnable = routeDescIsEnable.Default.(bool)
	// routeDescDeletedAt is the schema descriptor for deleted_at field.
	routeDescDeletedAt := routeMixinFields2[0].Descriptor()
	// route.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	route.DefaultDeletedAt = routeDescDeletedAt.Default.(int)
}

const (
	Version = "v0.13.1"                                         // Version of ent codegen.
	Sum     = "h1:uD8QwN1h6SNphdCCzmkMN3feSUzNnVvV/WIkHKMbzOE=" // Sum of ent codegen.
)
