// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gva/app/database/schema/pxid"
	"github.com/gva/internal/ent/manga"
	"github.com/gva/internal/ent/mangachapter"
	"github.com/gva/internal/ent/predicate"

	"github.com/gva/internal/ent/internal"
)

// MangaChapterQuery is the builder for querying MangaChapter entities.
type MangaChapterQuery struct {
	config
	ctx        *QueryContext
	order      []mangachapter.OrderOption
	inters     []Interceptor
	predicates []predicate.MangaChapter
	withManga  *MangaQuery
	loadTotal  []func(context.Context, []*MangaChapter) error
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MangaChapterQuery builder.
func (mcq *MangaChapterQuery) Where(ps ...predicate.MangaChapter) *MangaChapterQuery {
	mcq.predicates = append(mcq.predicates, ps...)
	return mcq
}

// Limit the number of records to be returned by this query.
func (mcq *MangaChapterQuery) Limit(limit int) *MangaChapterQuery {
	mcq.ctx.Limit = &limit
	return mcq
}

// Offset to start from.
func (mcq *MangaChapterQuery) Offset(offset int) *MangaChapterQuery {
	mcq.ctx.Offset = &offset
	return mcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mcq *MangaChapterQuery) Unique(unique bool) *MangaChapterQuery {
	mcq.ctx.Unique = &unique
	return mcq
}

// Order specifies how the records should be ordered.
func (mcq *MangaChapterQuery) Order(o ...mangachapter.OrderOption) *MangaChapterQuery {
	mcq.order = append(mcq.order, o...)
	return mcq
}

// QueryManga chains the current query on the "manga" edge.
func (mcq *MangaChapterQuery) QueryManga() *MangaQuery {
	query := (&MangaClient{config: mcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(mangachapter.Table, mangachapter.FieldID, selector),
			sqlgraph.To(manga.Table, manga.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, mangachapter.MangaTable, mangachapter.MangaColumn),
		)
		schemaConfig := mcq.schemaConfig
		step.To.Schema = schemaConfig.Manga
		step.Edge.Schema = schemaConfig.MangaChapter
		fromU = sqlgraph.SetNeighbors(mcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MangaChapter entity from the query.
// Returns a *NotFoundError when no MangaChapter was found.
func (mcq *MangaChapterQuery) First(ctx context.Context) (*MangaChapter, error) {
	nodes, err := mcq.Limit(1).All(setContextOp(ctx, mcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{mangachapter.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mcq *MangaChapterQuery) FirstX(ctx context.Context) *MangaChapter {
	node, err := mcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MangaChapter ID from the query.
// Returns a *NotFoundError when no MangaChapter ID was found.
func (mcq *MangaChapterQuery) FirstID(ctx context.Context) (id pxid.ID, err error) {
	var ids []pxid.ID
	if ids, err = mcq.Limit(1).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{mangachapter.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mcq *MangaChapterQuery) FirstIDX(ctx context.Context) pxid.ID {
	id, err := mcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MangaChapter entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MangaChapter entity is found.
// Returns a *NotFoundError when no MangaChapter entities are found.
func (mcq *MangaChapterQuery) Only(ctx context.Context) (*MangaChapter, error) {
	nodes, err := mcq.Limit(2).All(setContextOp(ctx, mcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{mangachapter.Label}
	default:
		return nil, &NotSingularError{mangachapter.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mcq *MangaChapterQuery) OnlyX(ctx context.Context) *MangaChapter {
	node, err := mcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MangaChapter ID in the query.
// Returns a *NotSingularError when more than one MangaChapter ID is found.
// Returns a *NotFoundError when no entities are found.
func (mcq *MangaChapterQuery) OnlyID(ctx context.Context) (id pxid.ID, err error) {
	var ids []pxid.ID
	if ids, err = mcq.Limit(2).IDs(setContextOp(ctx, mcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{mangachapter.Label}
	default:
		err = &NotSingularError{mangachapter.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mcq *MangaChapterQuery) OnlyIDX(ctx context.Context) pxid.ID {
	id, err := mcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MangaChapters.
func (mcq *MangaChapterQuery) All(ctx context.Context) ([]*MangaChapter, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryAll)
	if err := mcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MangaChapter, *MangaChapterQuery]()
	return withInterceptors[[]*MangaChapter](ctx, mcq, qr, mcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mcq *MangaChapterQuery) AllX(ctx context.Context) []*MangaChapter {
	nodes, err := mcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MangaChapter IDs.
func (mcq *MangaChapterQuery) IDs(ctx context.Context) (ids []pxid.ID, err error) {
	if mcq.ctx.Unique == nil && mcq.path != nil {
		mcq.Unique(true)
	}
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryIDs)
	if err = mcq.Select(mangachapter.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mcq *MangaChapterQuery) IDsX(ctx context.Context) []pxid.ID {
	ids, err := mcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mcq *MangaChapterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryCount)
	if err := mcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mcq, querierCount[*MangaChapterQuery](), mcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mcq *MangaChapterQuery) CountX(ctx context.Context) int {
	count, err := mcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mcq *MangaChapterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mcq.ctx, ent.OpQueryExist)
	switch _, err := mcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mcq *MangaChapterQuery) ExistX(ctx context.Context) bool {
	exist, err := mcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MangaChapterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mcq *MangaChapterQuery) Clone() *MangaChapterQuery {
	if mcq == nil {
		return nil
	}
	return &MangaChapterQuery{
		config:     mcq.config,
		ctx:        mcq.ctx.Clone(),
		order:      append([]mangachapter.OrderOption{}, mcq.order...),
		inters:     append([]Interceptor{}, mcq.inters...),
		predicates: append([]predicate.MangaChapter{}, mcq.predicates...),
		withManga:  mcq.withManga.Clone(),
		// clone intermediate query.
		sql:       mcq.sql.Clone(),
		path:      mcq.path,
		modifiers: append([]func(*sql.Selector){}, mcq.modifiers...),
	}
}

// WithManga tells the query-builder to eager-load the nodes that are connected to
// the "manga" edge. The optional arguments are used to configure the query builder of the edge.
func (mcq *MangaChapterQuery) WithManga(opts ...func(*MangaQuery)) *MangaChapterQuery {
	query := (&MangaClient{config: mcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mcq.withManga = query
	return mcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty" rql:"filter,sort"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MangaChapter.Query().
//		GroupBy(mangachapter.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mcq *MangaChapterQuery) GroupBy(field string, fields ...string) *MangaChapterGroupBy {
	mcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MangaChapterGroupBy{build: mcq}
	grbuild.flds = &mcq.ctx.Fields
	grbuild.label = mangachapter.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"createdAt,omitempty" rql:"filter,sort"`
//	}
//
//	client.MangaChapter.Query().
//		Select(mangachapter.FieldCreatedAt).
//		Scan(ctx, &v)
func (mcq *MangaChapterQuery) Select(fields ...string) *MangaChapterSelect {
	mcq.ctx.Fields = append(mcq.ctx.Fields, fields...)
	sbuild := &MangaChapterSelect{MangaChapterQuery: mcq}
	sbuild.label = mangachapter.Label
	sbuild.flds, sbuild.scan = &mcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MangaChapterSelect configured with the given aggregations.
func (mcq *MangaChapterQuery) Aggregate(fns ...AggregateFunc) *MangaChapterSelect {
	return mcq.Select().Aggregate(fns...)
}

func (mcq *MangaChapterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mcq); err != nil {
				return err
			}
		}
	}
	for _, f := range mcq.ctx.Fields {
		if !mangachapter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mcq.path != nil {
		prev, err := mcq.path(ctx)
		if err != nil {
			return err
		}
		mcq.sql = prev
	}
	return nil
}

func (mcq *MangaChapterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MangaChapter, error) {
	var (
		nodes       = []*MangaChapter{}
		_spec       = mcq.querySpec()
		loadedTypes = [1]bool{
			mcq.withManga != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MangaChapter).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MangaChapter{config: mcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	_spec.Node.Schema = mcq.schemaConfig.MangaChapter
	ctx = internal.NewSchemaConfigContext(ctx, mcq.schemaConfig)
	if len(mcq.modifiers) > 0 {
		_spec.Modifiers = mcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mcq.withManga; query != nil {
		if err := mcq.loadManga(ctx, query, nodes, nil,
			func(n *MangaChapter, e *Manga) { n.Edges.Manga = e }); err != nil {
			return nil, err
		}
	}
	for i := range mcq.loadTotal {
		if err := mcq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mcq *MangaChapterQuery) loadManga(ctx context.Context, query *MangaQuery, nodes []*MangaChapter, init func(*MangaChapter), assign func(*MangaChapter, *Manga)) error {
	ids := make([]pxid.ID, 0, len(nodes))
	nodeids := make(map[pxid.ID][]*MangaChapter)
	for i := range nodes {
		fk := nodes[i].MangaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(manga.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "manga_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mcq *MangaChapterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mcq.querySpec()
	_spec.Node.Schema = mcq.schemaConfig.MangaChapter
	ctx = internal.NewSchemaConfigContext(ctx, mcq.schemaConfig)
	if len(mcq.modifiers) > 0 {
		_spec.Modifiers = mcq.modifiers
	}
	_spec.Node.Columns = mcq.ctx.Fields
	if len(mcq.ctx.Fields) > 0 {
		_spec.Unique = mcq.ctx.Unique != nil && *mcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mcq.driver, _spec)
}

func (mcq *MangaChapterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(mangachapter.Table, mangachapter.Columns, sqlgraph.NewFieldSpec(mangachapter.FieldID, field.TypeString))
	_spec.From = mcq.sql
	if unique := mcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mcq.path != nil {
		_spec.Unique = true
	}
	if fields := mcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, mangachapter.FieldID)
		for i := range fields {
			if fields[i] != mangachapter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mcq.withManga != nil {
			_spec.Node.AddColumnOnce(mangachapter.FieldMangaID)
		}
	}
	if ps := mcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mcq *MangaChapterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mcq.driver.Dialect())
	t1 := builder.Table(mangachapter.Table)
	columns := mcq.ctx.Fields
	if len(columns) == 0 {
		columns = mangachapter.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mcq.sql != nil {
		selector = mcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mcq.ctx.Unique != nil && *mcq.ctx.Unique {
		selector.Distinct()
	}
	t1.Schema(mcq.schemaConfig.MangaChapter)
	ctx = internal.NewSchemaConfigContext(ctx, mcq.schemaConfig)
	selector.WithContext(ctx)
	for _, m := range mcq.modifiers {
		m(selector)
	}
	for _, p := range mcq.predicates {
		p(selector)
	}
	for _, p := range mcq.order {
		p(selector)
	}
	if offset := mcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (mcq *MangaChapterQuery) ForUpdate(opts ...sql.LockOption) *MangaChapterQuery {
	if mcq.driver.Dialect() == dialect.Postgres {
		mcq.Unique(false)
	}
	mcq.modifiers = append(mcq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return mcq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (mcq *MangaChapterQuery) ForShare(opts ...sql.LockOption) *MangaChapterQuery {
	if mcq.driver.Dialect() == dialect.Postgres {
		mcq.Unique(false)
	}
	mcq.modifiers = append(mcq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return mcq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mcq *MangaChapterQuery) Modify(modifiers ...func(s *sql.Selector)) *MangaChapterSelect {
	mcq.modifiers = append(mcq.modifiers, modifiers...)
	return mcq.Select()
}

// MangaChapterGroupBy is the group-by builder for MangaChapter entities.
type MangaChapterGroupBy struct {
	selector
	build *MangaChapterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mcgb *MangaChapterGroupBy) Aggregate(fns ...AggregateFunc) *MangaChapterGroupBy {
	mcgb.fns = append(mcgb.fns, fns...)
	return mcgb
}

// Scan applies the selector query and scans the result into the given value.
func (mcgb *MangaChapterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcgb.build.ctx, ent.OpQueryGroupBy)
	if err := mcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MangaChapterQuery, *MangaChapterGroupBy](ctx, mcgb.build, mcgb, mcgb.build.inters, v)
}

func (mcgb *MangaChapterGroupBy) sqlScan(ctx context.Context, root *MangaChapterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mcgb.fns))
	for _, fn := range mcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mcgb.flds)+len(mcgb.fns))
		for _, f := range *mcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MangaChapterSelect is the builder for selecting fields of MangaChapter entities.
type MangaChapterSelect struct {
	*MangaChapterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mcs *MangaChapterSelect) Aggregate(fns ...AggregateFunc) *MangaChapterSelect {
	mcs.fns = append(mcs.fns, fns...)
	return mcs
}

// Scan applies the selector query and scans the result into the given value.
func (mcs *MangaChapterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mcs.ctx, ent.OpQuerySelect)
	if err := mcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MangaChapterQuery, *MangaChapterSelect](ctx, mcs.MangaChapterQuery, mcs, mcs.inters, v)
}

func (mcs *MangaChapterSelect) sqlScan(ctx context.Context, root *MangaChapterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mcs.fns))
	for _, fn := range mcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mcs *MangaChapterSelect) Modify(modifiers ...func(s *sql.Selector)) *MangaChapterSelect {
	mcs.modifiers = append(mcs.modifiers, modifiers...)
	return mcs
}
